repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.10.4]
        args: [--install-types, --non-interactive]

  - repo: local
    hooks:
      - id: uv-check
        name: uv-check
        description: run uv check to validate pyproject.toml
        entry: uv
        args: [check]
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$
      
      - id: pytest-check
        name: pytest-check
        entry: python
        args: [-m, pytest]
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]